# Trial name: test.yaml
# ARIAC2024
# Author: 
# 2023-12-13 10:49:28

# ENVIRONMENT SETUP

time_limit: -1


kitting_trays:
  tray_ids:
  - 6
  - 1
  slots:
  - 1
  - 6


assembly_inserts:
  as1: -pi/3
  as2: '0'
  as3: 2*pi/3
  as4: '0'


parts:
  agvs:
    agv1:
      tray_id: 0
      parts:
      - type: blue
        color: battery
        quadrant: 1
  bins:
    bin1:
    - type: sensor
      color: green
      rotation: '0'
      flipped: false
      slots:
      - 5
      - 9
    bin7:
    - type: sensor
      color: green
      rotation: '0'
      flipped: false
      slots:
      - 3
      - 6
      - 8
  conveyor_belt:
    active: true
    spawn_rate: 1.0
    order: random
    parts_to_spawn:
    - type: sensor
      color: green
      number: 4
      offset: 0.0
      flipped: false
      rotation: pi/3


orders:
- id: EPPN4VMP
  type: assembly
  announcement:
    time_condition: 0.0
  priority: false
  assembly_task:
    agv_number:
    - 1
    - 3
    station: 0
    products:
    - type: battery
      color: blue
      assembled_pose:
        xyz:
        - -0.15
        - 0.035
        - 0.043
        rpy:
        - 0
        - 0
        - pi/2
      assembly_direction:
      - 0
      - 1
      - 0

