# Trial name: testing.yaml
# ARIAC2024
# Author: 
# 2024-02-21 12:46:30

# ENVIRONMENT SETUP

time_limit: 0

# KITTING TRAYS

kitting_trays:
  tray_ids: []
  slots: []

# INSERT ROTATION

assembly_inserts:
  as1: 0.0
  as2: 0.0
  as3: 0.0
  as4: 0.0

# PARTS INFORMATION

parts:
  bins:
    bin1:
    - type: battery
      color: blue
      rotation: 0.0
      flipped: false
      slots:
      - 1
      - 3
      - 7
      - 9
  conveyor_belt: # population params for conveyor belt
    active: true
    spawn_rate: 1.0 # seconds between spawn
    order: 'sequential' # random or sequential
    parts_to_spawn:
      - type: 'regulator'
        color: 'orange'
        number: 1
        offset: 0.5 # between -1 and 1
        flipped: false
        rotation: 'pi/6'

orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 3