controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    floor_robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    floor_robot_2_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    linear_rail_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    floor_robot_static_controller:
      type: ariac_controllers/StaticController
    
    floor_robot_2_static_controller:
      type: ariac_controllers/StaticController


floor_robot_controller:
  ros__parameters:
    joints:
      - floor_shoulder_pan_joint
      - floor_shoulder_lift_joint
      - floor_elbow_joint
      - floor_wrist_1_joint
      - floor_wrist_2_joint
      - floor_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      floor_shoulder_pan_joint: { trajectory: 0.5, goal: 0.1 }
      floor_shoulder_lift_joint: { trajectory: 0.5, goal: 0.1 }
      floor_elbow_joint: { trajectory: 0.5, goal: 0.1 }
      floor_wrist_1_joint: { trajectory: 0.5, goal: 0.1 }
      floor_wrist_2_joint: { trajectory: 0.5, goal: 0.1 }
      floor_wrist_3_joint: { trajectory: 0.5, goal: 0.1 }



floor_robot_2_controller:
  ros__parameters:
    joints:
      - floor_2_shoulder_pan_joint
      - floor_2_shoulder_lift_joint
      - floor_2_elbow_joint
      - floor_2_wrist_1_joint
      - floor_2_wrist_2_joint
      - floor_2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      floor_2_shoulder_pan_joint: { trajectory: 0.5, goal: 0.1 }
      floor_2_shoulder_lift_joint: { trajectory: 0.5, goal: 0.1 }
      floor_2_elbow_joint: { trajectory: 0.5, goal: 0.1 }
      floor_2_wrist_1_joint: { trajectory: 0.5, goal: 0.1 }
      floor_2_wrist_2_joint: { trajectory: 0.5, goal: 0.1 }
      floor_2_wrist_3_joint: { trajectory: 0.5, goal: 0.1 }

floor_robot_static_controller:
  ros__parameters:
    joints:
      - linear_actuator_joint
      - floor_shoulder_pan_joint
      - floor_shoulder_lift_joint
      - floor_elbow_joint
      - floor_wrist_1_joint
      - floor_wrist_2_joint
      - floor_wrist_3_joint

floor_robot_2_static_controller:
  ros__parameters:
    joints:
      - floor_2_shoulder_pan_joint
      - floor_2_shoulder_lift_joint
      - floor_2_elbow_joint
      - floor_2_wrist_1_joint
      - floor_2_wrist_2_joint
      - floor_2_wrist_3_joint

linear_rail_controller:
  ros__parameters:
    joints:
      - linear_actuator_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      linear_actuator_joint: {trajectory: 0.5, goal: 0.1}
