# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - floor_robot_controller
    - floor_robot_2_controller
    - linear_rail_controller

  floor_robot_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - floor_shoulder_pan_joint
      - floor_shoulder_lift_joint
      - floor_elbow_joint
      - floor_wrist_1_joint
      - floor_wrist_2_joint
      - floor_wrist_3_joint
  
  floor_robot_2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - floor_2_shoulder_pan_joint
      - floor_2_shoulder_lift_joint
      - floor_2_elbow_joint
      - floor_2_wrist_1_joint
      - floor_2_wrist_2_joint
      - floor_2_wrist_3_joint

  linear_rail_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - linear_actuator_joint